import "@/styles/globals.css";
import Providers from "./components/providers";
import { type Metadata } from "next";
import { Radio_Canada_Big } from "next/font/google";

const radioCanadaBig = Radio_Canada_Big({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-radio-canada-big",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${radioCanadaBig.variable}`}>
      <body className="h-screen antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
